name: Build and Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths:
      - '**'
      
jobs:  
  test:
    name: Run mock unit tests
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/stable:current
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2      
      - name: Run unit tests
        run:  python3 setup.py test
