name: Build and Test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths:
      - '**'
      
jobs:  
  test:
    name: "run mock unit tests"
    runs-on: ubuntu-latest
    container: precice/ci-ubuntu-1804
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 
      - name: "Install fake precice"
        run:  |
          mkdir -p precice && echo -e "from setuptools import setup\nsetup(name='pyprecice', version='2.0.2.1')" > precice/setup.py
          pip3 install --user ./precice/
      - name: "Run unit tests"
        run:  python3 setup.py test
